In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [29]:
def parse_datetime(array_str):
    vals = np.fromstring(array_str.strip('[]'), sep=' ')
    return datetime(
        int(vals[0]), int(vals[1]), int(vals[2]),
        int(vals[3]), int(vals[4]),
        int(vals[5]), int((vals[5] % 1) * 1_000_000)
    )

In [110]:
def read_clean_file(filepath):
    """
    input the filepath to the 'cleaned_dataset' folder
    ex: 'user/downloads/cleaned_dataset'
    """
    filepath += 'metadata.csv'
    df = pd.read_csv(filepath)
    df['start_time'] = df['start_time'].apply(parse_datetime)

In [39]:
filepath = "cleaned_dataset/metadata.csv"
df = pd.read_csv(filepath)
df['start_time'] = df['start_time'].apply(parse_datetime)

In [67]:
df

,type,start_time,ambient_temperature,battery_id,test_id,uid,filename,Capacity,Re,Rct
0,discharge,2010-07-21 15:00:35.093000,4,B0047,0,1,00001.csv,1.6743047446975208,NaN,NaN
1,impedance,2010-07-21 16:53:45.968000,24,B0047,1,2,00002.csv,NaN,0.05605783343888099,0.20097016584458333
2,charge,2010-07-21 17:25:40.670999,4,B0047,2,3,00003.csv,NaN,NaN,NaN
3,impedance,2010-07-21 20:31:05.000000,24,B0047,3,4,00004.csv,NaN,0.05319185850921101,0.16473399914864734
4,discharge,2010-07-21 21:02:56.984000,4,B0047,4,5,00005.csv,1.5243662105099023,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7560,impedance,2010-09-30 07:36:45.045999,24,B0055,247,7561,07561.csv,NaN,0.0968087979207628,0.15489738203707232
7561,discharge,2010-09-30 08:08:36.328000,4,B0055,248,7562,07562.csv,1.0201379996149256,NaN,NaN
7562,charge,2010-09-30 08:48:54.250000,4,B0055,249,7563,07563.csv,NaN,NaN,NaN
7563,discharge,2010-09-30 11:50:17.687000,4,B0055,250,7564,07564.csv,0.9907591663373165,NaN,NaN
7564,charge,2010-09-30 12:31:10.170999,4,B0055,251,7565,07565.csv,NaN,NaN,NaN

In [104]:
BATTERIES = sorted(df['battery_id'].value_counts().index.tolist())
len(BATTERIES)

34

In [106]:
df[df['battery_id'] == 'B0007']['type'].value_counts()

type
impedance    278
charge       170
discharge    168
Name: count, dtype: int64

In [65]:
df[(df['battery_id'] == 'B0007') & (df['type'] == 'discharge')]

,type,start_time,ambient_temperature,battery_id,test_id,uid,filename,Capacity,Re,Rct
5737,discharge,2008-04-02 15:25:41.593000,24,B0007,1,5738,05738.csv,1.89105229539079,NaN,NaN
5739,discharge,2008-04-02 19:43:48.405999,24,B0007,3,5740,05740.csv,1.880637027686859,NaN,NaN
5741,discharge,2008-04-03 00:01:06.687000,24,B0007,5,5742,05742.csv,1.8806626717011388,NaN,NaN
5743,discharge,2008-04-03 04:16:37.375000,24,B0007,7,5744,05744.csv,1.8807709009833444,NaN,NaN
5745,discharge,2008-04-03 08:33:25.702999,24,B0007,9,5746,05746.csv,1.8794508728285058,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
6335,discharge,2008-05-26 10:44:38.468000,24,B0007,599,6336,06336.csv,1.4061714290398801,NaN,NaN
6339,discharge,2008-05-26 15:30:43.968000,24,B0007,603,6340,06340.csv,1.4063358479692922,NaN,NaN
6343,discharge,2008-05-26 20:21:04.921000,24,B0007,607,6344,06344.csv,1.4004552399066514,NaN,NaN
6347,discharge,2008-05-27 15:52:41.359000,24,B0007,611,6348,06348.csv,1.4217865046055154,NaN,NaN
6349,discharge,2008-05-27 20:45:42.125000,24,B0007,613,6350,06350.csv,1.4324552720625434,NaN,NaN